version: "3"
services:
    backend:
        build: backend
        expose:
            - 8000
        volumes:
            - ./data:/data

    frontend:
        build: frontend
        depends_on:
            - backend
        ports:
            - "127.0.0.1:5000:80"
